# Generated by Django 4.0.4 on 2022-10-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asigm_1_app', '0002_manufacturer_personn_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name_car',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='name_manu',
            field=models.CharField(default='SOMESTRING', max_length=255),
        ),
    ]
